### ISSUE TITLE
Code Regarding MEMAE anomaly detection

### ISSUE THREAD

**Issue by saikumarkethi** [VieVie31/cool-papers-in-pytorch#5]
Can you share me MemAE anomaly detection code please

**Comment by VieVie31** [comment]
Hi,

[There](https://github.com/VieVie31/cool-papers-in-pytorch/blob/master/memoryzing_normality_to_detect_anomaly.py) is the file you might look for.
Maybe you'll also be interested by the author code which you can find [here](https://github.com/donggong1/memae-anomaly-detection).

Best Regards,
Olivier
